### ISSUE TITLE
JS/Wasm Support

### ISSUE THREAD

**Issue by skaldebane** [adamglin0/compose-phosphor-icon#1]
Hi there!
Would love to see this support JS/Wasm targets.

As far as I'm aware, just like material icons, they're not using any platform-specific APIs (just paths).
So are there some other hurdles blocking this? I can submit a PR.

And thanks for the library!

**Comment by adamglin0** [comment]
Thank you for your feedback, there is no difficulty at all. Only a small amount of Kotlin configuration is needed.
Welcome any PRs!!!

**Comment by skaldebane** [comment]
Is it alright to update and clean up dependencies at the same time?

**Comment by adamglin0** [comment]
> Is it alright to update and clean up dependencies at the same time?

Yes❤️, please submit any code you think is correct. However, it would be better if you could separate the submission of adding targets and dependencies cleanup.

**Comment by skaldebane** [comment]
Ah alright, will do!

**Comment by skaldebane** [comment]
@adamglin0 This configuration
```kotlin
repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
```
in `settings.gradle.kts` prevents Gradle from downloading Node.js (to run JS samples).

Is there any harm in removing it?

**Comment by skaldebane** [comment]
Or would using pre-installed Node.js / Yarn be preferred, as in these docs: https://kotlinlang.org/docs/whatsnew16.html#option-to-use-pre-installed-node-js-and-yarn

**Comment by adamglin0** [comment]
> @adamglin0 This configuration
> 
> ```kotlin
> 
> repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
> 
> ```
> 
> in `settings.gradle.kts` prevents Gradle from downloading Node.js (to run JS samples).
> 
> 
> 
> Is there any harm in removing it?

I have no idea about the conf prevents kotlin/js download nodejs. Is there docs or exceptions?

**Comment by skaldebane** [comment]
@adamglin0 Trying to run JS/Wasm samples results in this error:

```
Build was configured to prefer settings repositories over project repositories but
repository 'Distributions at https://nodejs.org/dist' was added by unknown code
```

And I found a Slack thread linking to the docs above (about using pre-installed versions) as the solution if that's not desired.

Anyhoo, I just out-commented that line and it worked.
