### ISSUE TITLE
Use proper CamelCase names for icons

### ISSUE THREAD

**Issue by skaldebane** [adamglin0/compose-phosphor-icon#6]
Hi there!

The current icon names feel quite un-natural to use, because the words don't start with capital letters (i.e. aren't proper CamelCase) 

e.g. `Magnifingglass` should be `MagnifyingGlass`:

![image](https://github.com/user-attachments/assets/6d23f5ed-4bc1-46c2-b8d1-db559e7ce2c6)

This of course is an API breaking change (would require a major version bump), but it's quite important to match Kotlin code style guidelines.

Smoothest way to do this is to rename all of the icons to be proper CamelCase, and make the old names alias to the new ones, and deprecate the old names (using Kotlin's `replaceWith` for automatic replacements), in a minor version bump (e.g. v1.1), before removing them completely in a major version bump (v2.0).

It's better to fix this earlier than later when more users are already relying on it :D

**Comment by adamglin0** [comment]
I plan to release a new version, and the name change will be considered an API breaking change, as there are currently few users, and this library is not expected to have more features in the future, just synchronizing the version of phosphor icons.
